/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FastingRouteImport } from './routes/fasting'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KhatmahRouteImport } from './routes/khatmah'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LocationRouteImport } from './routes/location'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AthkarIndexRouteImport } from './routes/athkar.index'
import { Route as AthkarCategoryIdRouteImport } from './routes/athkar.$categoryId'
import { Route as AthkarTasbihRouteImport } from './routes/athkar.tasbih'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahIdRouteImport } from './routes/quran.$surahId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FastingRoute = FastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KhatmahRoute = KhatmahRouteImport.update({
  id: '/khatmah',
  path: '/khatmah',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AthkarIndexRoute = AthkarIndexRouteImport.update({
  id: '/athkar/',
  path: '/athkar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthkarCategoryIdRoute = AthkarCategoryIdRouteImport.update({
  id: '/athkar/$categoryId',
  path: '/athkar/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AthkarTasbihRoute = AthkarTasbihRouteImport.update({
  id: '/athkar/tasbih',
  path: '/athkar/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahIdRoute = QuranSurahIdRouteImport.update({
  id: '/quran/$surahId',
  path: '/quran/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/fasting': typeof FastingRoute
  '/journal': typeof JournalRoute
  '/khatmah': typeof KhatmahRoute
  '/library': typeof LibraryRoute
  '/location': typeof LocationRoute
  '/prayer': typeof PrayerRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/athkar/$categoryId': typeof AthkarCategoryIdRoute
  '/athkar/tasbih': typeof AthkarTasbihRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/athkar/': typeof AthkarIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/fasting': typeof FastingRoute
  '/journal': typeof JournalRoute
  '/khatmah': typeof KhatmahRoute
  '/library': typeof LibraryRoute
  '/location': typeof LocationRoute
  '/prayer': typeof PrayerRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/athkar/$categoryId': typeof AthkarCategoryIdRoute
  '/athkar/tasbih': typeof AthkarTasbihRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/athkar': typeof AthkarIndexRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/fasting': typeof FastingRoute
  '/journal': typeof JournalRoute
  '/khatmah': typeof KhatmahRoute
  '/library': typeof LibraryRoute
  '/location': typeof LocationRoute
  '/prayer': typeof PrayerRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/athkar/$categoryId': typeof AthkarCategoryIdRoute
  '/athkar/tasbih': typeof AthkarTasbihRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/athkar/': typeof AthkarIndexRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/fasting'
    | '/journal'
    | '/khatmah'
    | '/library'
    | '/location'
    | '/prayer'
    | '/qibla'
    | '/settings'
    | '/api/chat'
    | '/athkar/$categoryId'
    | '/athkar/tasbih'
    | '/quran/$surahId'
    | '/athkar/'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/fasting'
    | '/journal'
    | '/khatmah'
    | '/library'
    | '/location'
    | '/prayer'
    | '/qibla'
    | '/settings'
    | '/api/chat'
    | '/athkar/$categoryId'
    | '/athkar/tasbih'
    | '/quran/$surahId'
    | '/athkar'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/fasting'
    | '/journal'
    | '/khatmah'
    | '/library'
    | '/location'
    | '/prayer'
    | '/qibla'
    | '/settings'
    | '/api/chat'
    | '/athkar/$categoryId'
    | '/athkar/tasbih'
    | '/quran/$surahId'
    | '/athkar/'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FastingRoute: typeof FastingRoute
  JournalRoute: typeof JournalRoute
  KhatmahRoute: typeof KhatmahRoute
  LibraryRoute: typeof LibraryRoute
  LocationRoute: typeof LocationRoute
  PrayerRoute: typeof PrayerRoute
  QiblaRoute: typeof QiblaRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  AthkarCategoryIdRoute: typeof AthkarCategoryIdRoute
  AthkarTasbihRoute: typeof AthkarTasbihRoute
  QuranSurahIdRoute: typeof QuranSurahIdRoute
  AthkarIndexRoute: typeof AthkarIndexRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasting': {
      id: '/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof FastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khatmah': {
      id: '/khatmah'
      path: '/khatmah'
      fullPath: '/khatmah'
      preLoaderRoute: typeof KhatmahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athkar/': {
      id: '/athkar/'
      path: '/athkar'
      fullPath: '/athkar/'
      preLoaderRoute: typeof AthkarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athkar/$categoryId': {
      id: '/athkar/$categoryId'
      path: '/athkar/$categoryId'
      fullPath: '/athkar/$categoryId'
      preLoaderRoute: typeof AthkarCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athkar/tasbih': {
      id: '/athkar/tasbih'
      path: '/athkar/tasbih'
      fullPath: '/athkar/tasbih'
      preLoaderRoute: typeof AthkarTasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surahId': {
      id: '/quran/$surahId'
      path: '/quran/$surahId'
      fullPath: '/quran/$surahId'
      preLoaderRoute: typeof QuranSurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FastingRoute: FastingRoute,
  JournalRoute: JournalRoute,
  KhatmahRoute: KhatmahRoute,
  LibraryRoute: LibraryRoute,
  LocationRoute: LocationRoute,
  PrayerRoute: PrayerRoute,
  QiblaRoute: QiblaRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  AthkarCategoryIdRoute: AthkarCategoryIdRoute,
  AthkarTasbihRoute: AthkarTasbihRoute,
  QuranSurahIdRoute: QuranSurahIdRoute,
  AthkarIndexRoute: AthkarIndexRoute,
  QuranIndexRoute: QuranIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
